---
cache:
  dir: "/tmp/.trivy-cache"

ignorefile: ".trivyignore.yml"

insecure: true

scan:
  parallel: 8
  skip-dirs:
    - .ansible
    - .cache
    - .pytest_cache
    - .ruff_cache
    - .terraform
    - .venv
    - common/.ansible
    - common/.terraform
    - data
    - logs
    - tmp
