[project]
name = "terraform_provider_sshkey"
version = "0.0.0"
description = "sshkey TF provider"
readme = "README.md"
requires-python = ">=3.12,<4.0"
license = "Apache-2.0"
dependencies = []

[[project.authors]]
name = "Justin Lecher"
email = "justin@jlec.de"

[dependency-groups]
dev = [
  "bpython>=0.26",
  "ptpython>=3.0.32",
  "pytest>=9.0.3",
  "pytest-asyncio>=1.4.0",
  "pytest-clarity>=1.0.1",
  "pytest-xdist>=3.8.0",
]

[tool.ruff]
line-length = 128
target-version = "py314"

[tool.ruff.format]
indent-style = "space"
quote-style = "double"

[tool.ruff.lint]
ignore = ["B008", "C901"]
select = ["B", "C", "E", "F", "I", "W"]

[tool.ruff.lint.per-file-ignores]
