---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

env:
  GO_NAME: sshkey
  GO_RUNNER: go
  GOOS: darwin
  GOARCH: arm64
  PY_PM: uv
  PY_RUNNER: uv run
  TF_NAMESPACE: dev
  TF_TYPE: sshkey
  TF_VERSION: "0.1.11"

tasks:
  default:
    cmds:
      - cmd: task -l

  #############################################################################
  #
  # Environment Setup
  #
  #############################################################################
  setup:
    desc: Setup environment
    cmds:
      - task: setup-python
      - task: setup-pre-commit

  setup-python:
    desc: Setup Python environment including dev dependencies
    cmds:
      - cmd: $PY_PM sync --upgrade --dev

  setup-pre-commit:
    desc: Setup Pre-Commit environment
    cmds:
      - cmd: $PY_RUNNER pre-commit install
      - cmd: $PY_RUNNER pre-commit install --install-hooks
      - cmd: $PY_RUNNER pre-commit install --hook-type commit-msg
      - cmd: $PY_RUNNER pre-commit install --hook-type pre-push
      - task: ansible-init

  ansible-init:
    desc: Setup ansible
    cmds:
      - cmd: echo "No Ansible support"
  #############################################################################
  #
  # Release management
  #
  #############################################################################
  release:
    desc: Release MINOR version bump
    cmds:
      - cmd: $PY_RUNNER cz bump --check-consistency --increment MINOR --no-verify

  release-major:
    desc: Release MAJOR version bump
    cmds:
      - cmd: $PY_RUNNER cz bump --check-consistency --increment MAJOR --no-verify

  release-patch:
    desc: Release PATCH version bump
    cmds:
      - cmd: $PY_RUNNER cz bump --check-consistency --increment PATCH --no-verify

  publish:
    desc: Push to remote
    cmds:
      - cmd: git push -v --progress
      - cmd: git push -v --progress --tags

  #############################################################################
  #
  # Cookies options
  #
  #############################################################################
  cruft-update:
    desc: Update the cookies
    cmds:
      - cmd: git stash push -m cruft-update
      - cmd: $PY_RUNNER cruft update --allow-untracked-files --skip-apply-ask
      - cmd: if test -d control; then pushd control >/dev/null && task init && popd; fi
      - cmd: if test -d deployment; then pushd deployment >/dev/null && task init && popd; fi
      - task: prettier
      - cmd: $PY_RUNNER pre-commit run -a terraform_docs
      - cmd: git stash list | grep -q cruft-update && git stash pop >/dev/null || true

  cruft-push:
    desc: Push the cookies
    cmds:
      - cmd: 'git ci -a -m "chore(cruft): update to latest cruft state"'

  cruft-reset:
    desc: Reset cruft
    cmds:
      - cmd: cruft diff | git apply

  #############################################################################
  #
  # Checking and Linting
  #
  #############################################################################
  prettier:
    desc: Run prettier
    cmds:
      - cmd: prettier -w .
  check:
    desc: Run pre-commit
    deps:
      - lint
  lint:
    desc: Run pre-commit
    deps:
      - linting
  linting:
    desc: Run pre-commit
    cmds:
      - task: pre-commit

  pre-commit:
    desc: Run pre-commit
    cmds:
      - cmd: $PY_RUNNER pre-commit run --hook-stage commit --all-files
      - cmd: $PY_RUNNER pre-commit run --hook-stage push --all-files
      - cmd: $PY_RUNNER pre-commit run --hook-stage manual --all-files

  test:
    desc: Run pytest
    deps:
      - pytest

  pytest:
    desc: Run pytest
    cmds:
      - cmd: $PY_RUNNER pytest
  #############################################################################
  #
  # GOLANG options
  #
  #############################################################################
  go-fmt:
    desc: Runs gofumpt
    sources:
      - "./**/*.go"
    cmds:
      - cmd: gofumpt -l -w -extra .

  go-install:
    desc: Install GO application
    sources:
      - "./**/*.go"
    cmds:
      - cmd: $GO_RUNNER install -v -ldflags="-w -s -X main.version=\{\{.GIT_COMMIT\}\}" ./cmd/${GO_NAME}

  go-lint:
    desc: Runs golangci-lint
    sources:
      - "./**/*.go"
    cmds:
      - cmd: golangci-lint --verbose run
      - cmd: staticcheck -f stylish ./...

  go-mod:
    desc: Downloads and tidy Go modules
    cmds:
      - cmd: go mod download -x
      - cmd: go mod tidy -v

  go-test:
    desc: Runs gotest
    cmds:
      - cmd: grc -es --colour=on go test -v --bench=. --benchmem ./...

  go-update:
    desc: Update dependencies
    cmds:
      - cmd: go get -u ./...

  go-vet:
    desc: Vet go code
    cmds:
      - cmd: go mod vendor
      - cmd: go vet ./...

  go-generate:
    desc: Generate GO docs and stuff
    cmds:
      - cmd: go mod vendor
      - cmd: go generate ./...
      - cmd: pre-commit run -a end-of-file-fixer
        ignore_error: true
      - cmd: pre-commit run -a trailing-whitespace
        ignore_error: true
      - cmd: prettier -w docs
        ignore_error: true
      - cmd: pre-commit run -a terraform_docs
        ignore_error: true

  ghost:
    desc: Run all go stuff
    cmds:
      - task: go-update
      - task: go-mod
      - task: go-generate
      - task: go-vet
      - task: go-fmt
      - task: go-lint
  #############################################################################
  #
  # Terraform provider
  #
  #############################################################################
  create-provider-dir:
    desc: Create Provider directory
    cmds:
      - cmd: mkdir -p ~/.terraform.d/plugins/jlec.de/${TF_NAMESPACE}/${TF_TYPE}/${TF_VERSION}/darwin_arm64

  provider-build:
    desc: Build project
    cmds:
      - cmd: go build -v -x -o ./terraform-provider-${TF_TYPE}_${TF_VERSION}_${GOOS}_${GOARCH}

  provider-install:
    desc: Install Terraform provider dev version
    deps:
      - provider-build
      - create-provider-dir
    cmds:
      - >-
        install -m 755
        ./terraform-provider-${TF_TYPE}_${TF_VERSION}_${GOOS}_${GOARCH}
        ~/.terraform.d/plugins/jlec.de/${TF_NAMESPACE}/${TF_TYPE}/${TF_VERSION}/darwin_arm64/terraform-provider-${TF_TYPE}_${TF_VERSION}_${GOOS}_${GOARCH}

  #############################################################################
  #
  # Custom options
  #
  #############################################################################
  clean:
    desc: Clean up
    cmds:
      - cmd: rm -rf dist
      - cmd: rm -rf tmp
      - cmd: git clean -fdx
